kind: Deployment
apiVersion: apps/v1
metadata:
  name: capstone
  labels:
    app: capstone

spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      name: capstone
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone-container
          image: himanshu1018/assignments:$BUILD_NUMBER
          ports:
            - containerPort: 8080
       


